# Generated by Django 5.2.3 on 2025-06-23 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_likedmovie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedmovie',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='likedmovie',
            name='liked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likedmovie',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='likedmovie',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likedmovie',
            name='vote_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='likedmovie',
            name='movie_id',
            field=models.CharField(max_length=50),
        ),
    ]
