# Generated by Django 5.2.3 on 2025-06-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_alter_likedmovie_unique_together_likedmovie_liked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top1000Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('released_year', models.IntegerField(blank=True, null=True)),
                ('runtime', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('star1', models.CharField(blank=True, max_length=255, null=True)),
                ('star2', models.CharField(blank=True, max_length=255, null=True)),
                ('star3', models.CharField(blank=True, max_length=255, null=True)),
                ('star4', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
